FROM scratch

# Copy the compiled binary into the container.  Crucially, it's statically linked.
COPY simplerouter /simplerouter
COPY .env /

# Expose the port (this is metadata, but good practice).
EXPOSE 8080

# Run the application.
ENTRYPOINT ["/simplerouter"]
